# ============================================================
#  TaskFlow — Dockerfile Frontend (Nginx + HTML/CSS/JS)
#  Linguagem: Dockerfile
# ============================================================

FROM nginx:1.27-alpine

# Remove config padrão do nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia arquivos do frontend
COPY frontend/ /usr/share/nginx/html/

# Copia configuração do nginx
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s \
    CMD wget --quiet --tries=1 --spider http://localhost/health || exit 1

CMD ["nginx", "-g", "daemon off;"]
